const PREFIX = '@salao/';

const types = {
  GET_SALAO: `${PREFIX}GET`,
  UPDATE_SALAO: `${PREFIX}UPDATE`,
  ALL_SERVICOS: `${PREFIX}ALL_SERVICOS`,
  UPDATE_SERVICOS: `${PREFIX}UPDATE_SERVICOS`,
  UPDATE_AGENDAMENTO: `${PREFIX}UPDATE_AGENDAMENTO`,
  UPDATE_FORM: `${PREFIX}UPDATE_FORM`,
  FILTER_AGENDA: `${PREFIX}FILTER_AGENDA`,
  UPDATE_AGENDA: `${PREFIX}UPDATE_AGENDA`,
  UPDATE_COLABORADORES: `${PREFIX}UPDATE_COLABORADORES`,
  RESET_AGENDAMENTO: `${PREFIX}RESET_AGENDAMENTO`,
  SAVE_AGENDAMENTO: `${PREFIX}SAVE_AGENDAMENTO`,
};

export default types;
